version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: magento-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: magento-mailhog
      ports:
        - "8061:8025"

    redis:
      image: redis:alpine
      container_name: magento-redis

    mysql:
      image: mysql:5.7
      container_name: magento-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8062:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: magento-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: magento-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8060:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: magento-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

